export const permissions = [
  "campground.configuration",
  "campground.map",
  "campground.map.publish",
  "accommodation.read",
  "accommodation.manage",
  "accommodation.media.manage",
  "reservation.read",
  "reservation.create",
  "reservation.modify",
  "reservation.cancel",
  "reservation.override",
  "pricing.manage",
  "payment.read",
  "payment.capture",
  "refund.issue",
  "discount.apply",
  "guest.read",
  "guest.manage",
  "vehicle.read",
  "vehicle.register",
  "vehicle.pass.issue",
  "visitor.read",
  "visitor.register",
  "access.credential.issue",
  "access.credential.revoke",
  "access.events.read",
  "gate.state.read",
  "gate.override.open",
  "gate.override.close",
  "security.incident.manage",
  "maintenance.read",
  "maintenance.create",
  "maintenance.assign",
  "maintenance.complete",
  "inspection.perform",
  "inspection.signoff",
  "seasonal.manage",
  "winterization.signoff",
  "permanent_unit.manage",
  "permanent_unit.transfer",
  "financing.read",
  "financing.manage",
  "event.manage",
  "event.access.manage",
  "local_interest.manage",
  "promotion.manage",
  "waterfront.manage",
  "boat.manage",
  "dock.manage",
  "safety.warning.issue",
  "safety.suspension.issue",
  "safety.suspension.review",
  "rental.manage",
  "pos.sell",
  "pos.refund",
  "inventory.read",
  "inventory.manage",
  "garbage.pickup.manage",
  "staff.read",
  "staff.manage",
  "role.manage",
  "schedule.manage",
  "timekeeping.manage",
  "vendor.read",
  "vendor.manage",
  "finance.read",
  "finance.manage",
  "reports.read",
  "audit.read",
  "announcement.send",
  "communications.read",
  "communications.send",
  "communications.manage",
  "voice.call",
  "ivr.admin",
  "sms.send",
  "sms.preference.manage",
  "emergency.broadcast",
  "it.health.read",
  "it.diagnostics.read",
  "it.incident.manage",
  "it.integration.read",
  "it.release.read",
  "it.diagnostics.export",
  "system.status.publish",
  "system.admin",
] as const;

export type Permission = (typeof permissions)[number];

const permissionSet = new Set<string>(permissions);

export function isPermission(value: string): value is Permission {
  return permissionSet.has(value);
}
